# This is a basic workflow to help you get started with Actions

name: linux_build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install needed software
        run: |
          sudo apt-get install perlbrew
          perlbrew init
          source ~/perl5/perlbrew/etc/bashrc
          perlbrew --notest install "5.32.1"
          wget -q https://github.com/majorendian/perl-Program/archive/refs/heads/master.zip -O program.zip
          unzip -x program.zip
          perlbrew switch "5.32.1" && cd perl-Program-master && perl Makefile.PL && make install && cd ..

      - name: Test the code with `prove`
        run: | 
          source ~/perl5/perlbrew/etc/bashrc
          perlbrew switch "5.32.1"
          prove -v
          
